---
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  opsgenie_api_url: https://api.opsgenie.com/
route:
  group_wait: 60s
  group_interval: 5m
  group_by: [alertname, environment]
  repeat_interval: 4h
  routes:
  # First, filter all testing alerts to that team in opsgenie
  - matchers:
    - testing="true"
    routes:
    - matchers:
      - severity="warning"
      receiver:  opsgenie-testing-p3
      continue: false
    - matchers:
      - severity="critical"
      receiver: opsgenie-testing-p2
      continue: false
    receiver: oblivion 
    continue: false

  # Now process real alerts
  - matchers:
    - dont_resolve="true"
    routes:
    - matchers:
      - severity="warning"
      receiver:  opsgenie-warning-no-auto-resolve
      continue: false
    - matchers:
      - severity="critical"
      receiver: opsgenie-critical-no-auto-resolve
      continue: false
    receiver: oblivion 
    continue: false

  - matchers:
    - channel="notifications-ocw-misc"
    routes:
    - matchers:
      - severity="warning"
      receiver: slack-notifications-ocw-misc-warning
      continue: false
    - matchers:
      - severity="critical"
      receiver: slack-notifications-ocw-misc-critical
      continue: false
    receiver: oblivion 
    continue: false

  - matchers:
    - severity="warning"
    receiver: opsgenie-warning
    continue: false
  - matchers:
    - severity="critical"
    receiver: opsgenie-critical
    continue: false
  receiver: oblivion
  continue: false

receivers:
# A null receiver for default messages.
- name: oblivion

- name: slack-notifications-ocw-misc-warning
  slack_configs:
  - send_resolved: true
    api_url: '%% SLACK_NOTIFICATIONS_OCW_MISC_API_URL %%'
    channel: '#notifications-ocw-misc'
    color: 'warning'
    icon_emoji: ':goose_warning:'
    title: '[{{ .Status | toUpper }}:{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end }}] - {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
        {{- if .Annotations.message }}
            {{ .Annotations.message }}
        {{- end }}
        {{- if .Annotations.description }}
            {{ .Annotations.description }}
        {{- end }}
      {{- end }}

- name: slack-notifications-ocw-misc-critical
  slack_configs:
  - send_resolved: true
    api_url: '%% SLACK_NOTIFICATIONS_OCW_MISC_API_URL %%'
    channel: '#notifications-ocw-misc'
    color: 'danger'
    icon_emoji: ':alert:'
    title: '[{{ .Status | toUpper }}:{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end }}] - {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
        {{- if .Annotations.message }}
            {{ .Annotations.message }}
        {{- end }}
        {{- if .Annotations.description }}
            {{ .Annotations.description }}
        {{- end }}
      {{- end }}

# Non-critical alerts (don't wake anyone up for this)
- name: opsgenie-warning
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p3"
    responders:
    - type: team
      name: 'ops_team'
# Critical alerts (wake someone up for this)
- name: opsgenie-critical
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p1"
    responders:
    - type: team
      name: 'ops_team'

# Non-critical alerts (don't wake anyone up for this)
- name: opsgenie-warning-no-auto-resolve
  opsgenie_configs:
  - send_resolved: false
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p3"
    responders:
    - type: team
      name: 'ops_team'
# Critical alerts (wake someone up for this)
- name: opsgenie-critical-no-auto-resolve
  opsgenie_configs:
  - send_resolved: false
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p1"
    responders:
    - type: team
      name: 'ops_team'

# These receivers all point to a different team in ops genie that doesn't really go anywhere
# but it will generate an alert with a history we can look at. 
- name: opsgenie-testing-p1
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p1"
    responders:
    - type: team
      name: 'testing'
- name: opsgenie-testing-p2
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p2"
    responders:
    - type: team
      name: 'testing'
- name: opsgenie-testing-p3
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p3"
    responders:
    - type: team
      name: 'testing'
templates: []
