---
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  opsgenie_api_url: https://api.opsgenie.com/
route:
  group_wait: 30s
  group_interval: 5m
  group_by: [alertname]
  repeat_interval: 4h
  routes:
  - matchers:
    - severity="warning"
    receiver: opsgenie-warning
  - matchers:
    - severity="critical"
    receiver: opsgenie-critical
  receiver: oblivion
  continue: false
receivers:
# A null receiver for default messages.
- name: oblivion
# Non-critical alerts (don't wake anyone up for this)
- name: opsgenie-warning
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p3"
    responders:
    - type: team
      name: 'ops_team'
# Critical alerts (wake someone up for this)
- name: opsgenie-critical
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% OPS_TEAM_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p1"
    responders:
    - type: team
      name: 'ops_team'
- name: opsgenie-testing-p1
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p1"
    responders:
    - type: team
      name: 'testing'
- name: opsgenie-testing-p2
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p2"
    responders:
    - type: team
      name: 'testing'
- name: opsgenie-testing-p3
  opsgenie_configs:
  - send_resolved: true
    api_key: '%% TESTING_OPS_GENIE_API_KEY %%'
    message: '{{ template "opsgenie.default.message" . }}'
    description: '{{ template "opsgenie.default.description" . }}'
    priority: "p3"
    responders:
    - type: team
      name: 'testing'
templates: []
