---
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  opsgenie_api_url: https://api.opsgenie.com/
route:
  group_wait: 60s
  group_interval: 5m
  group_by: [alertname, environment]
  repeat_interval: 4h
  routes:
  # First, filter all testing alerts to that team in opsgenie
  - matchers:
    - channel="notifications-ocw-misc"
    routes:
    - matchers:
      - severity="warning"
      receiver: slack-notifications-ocw-misc-warning
      continue: false
    - matchers:
      - severity="critical"
      receiver: slack-notifications-ocw-misc-critical
      continue: false
    receiver: oblivion 
    continue: false

  - matchers:
    - severity="warning"
    receiver: rootly
    continue: false
  - matchers:
    - severity="critical"
    receiver: rootly
    continue: false
  receiver: oblivion
  continue: false

receivers:
# A null receiver for default messages.
- name: oblivion

- name: slack-notifications-ocw-misc-warning
  slack_configs:
  - send_resolved: true
    api_url: '%% SLACK_NOTIFICATIONS_OCW_MISC_API_URL %%'
    channel: '#notifications-ocw-misc'
    color: 'warning'
    icon_emoji: ':goose_warning:'
    title: ':goose_warning: [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end }}] - {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
        {{- if .Annotations.message }}
            Message - {{ .Annotations.message }}
        {{- end }}
        {{- if .Annotations.description }}
            Description - {{ .Annotations.description }}
        {{- end }}
        {{- if .Annotations.summary }}
            Summary - {{ .Annotations.summary }}
        {{- end }}
      {{- end }}

- name: slack-notifications-ocw-misc-critical
  slack_configs:
  - send_resolved: true
    api_url: '%% SLACK_NOTIFICATIONS_OCW_MISC_API_URL %%'
    channel: '#notifications-ocw-misc'
    color: 'danger'
    title: ':alert: [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end }}] - {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
        {{- if .Annotations.message }}
            {{ .Annotations.message }}
        {{- end }}
        {{- if .Annotations.description }}
            {{ .Annotations.description }}
        {{- end }}
      {{- end }}

# Non-critical alerts (don't wake anyone up for this)
- name: rootly
  webhook_configs:
  - url: 'https://webhooks.rootly.com/webhooks/incoming/alertmanager_webhooks'
    send_resolved: true
    http_config:
      authorization:
        type: Bearer
        credentials: '%% ROOTLY_BEARER_TOKEN %%'
templates: []
